config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :materials do
    resource :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :material

    validates_uniqueness_of :material_id, scope: :user_id
    validates :material_id,{presence: true}
    validates :user_id,{presence: true}
end

app/models/material.rb
class Material < ApplicationRecord
    belongs_to :user
    attachment :image
    mount_uploader :video, VideoUploader
    has_many :likes, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
        validates :video
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :materials, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :username, presence: true

  def already_liked?(material)
    self.likes.exists?(material_id: material.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
       @like = current_user.likes.create(material_id: params[:material_id])
      redirect_back(fallback_location: root_path)
    end
    
    def destroy
      @material = Material.find(params[:material_id])
      @like = current_user.likes.find_by(material_id: @material.id)
      @like.destroy
      redirect_back(fallback_location: root_path)
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @materials = Material.all
  end

  def show
    @material = Material.find(params[:id])
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    @material.user_id = current_user.id
    if @material.save
      redirect_to material_path(@material), notice: "投稿に成功しました"
    else
      render :new
    end
  end


  def edit
    @material = Material.find(params[:id])
    if @material.user != current_user
      redirect_to materials_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @material = Material.find(params[:id])
    if @material.update(material_params)
      redirect_to material_path(@material), notice: "レシピを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @material = Material.find_by(params[:id])
    @material.destroy
    redirect_to material_path
  end

  private
  def material_params
    params.require(:material).permit(:title, :body, :image, :video)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
  end


  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新に成功しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: sans-serif;">素材天国</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-info is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-info is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <div class="colums is-centered">
    <div class="column is-3">サンプルメールアドレス:user@sample.com</div>
    <div class="column is-3">サンプルパスワード:password</div>
  </div>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

<div>
  使用Gem
  <div>devise  refile  refile-mini_magick  bulma-rails carrierwave <div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>素材天国</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
        <div class="notification is-info">
          <p class="notice"><%= notice %></p>
        </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-danger">
      <div class="navbar-brand">
        <%= link_to(root_path, class: "navbar-item") do %>
          <h1 class="title is-4" style="font-family: sans-serif;">素材天国</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

    <% if user_signed_in? %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-item">
        <%= link_to "素材一覧", materials_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-item">
        <%= link_to "新規投稿", new_material_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "投稿者一覧", users_path, class: "button is-warning is-light" %>
            </p>
            <p class="control">
              <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
            </p>
            <p class="control">
              <%= link_to("ログアウト",destroy_user_session_path, method: :delete, class: "button is-warning is-light") %>
            </p>
          </div>
        </div>
      </div>


    </div>
    <% else %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-item">
        <%= link_to "素材一覧", materials_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-item">
      <%= link_to "投稿者一覧", users_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to("ログイン",new_user_session_path, class: "button is-warning is-light") %>
            </p>
            <p class="control">
              <%= link_to("新規登録",new_user_registration_path, class: "button is-warning is-light") %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/materials/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">素材編集</h1>
    </div>
  </div>
</section>

<% if @material.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@material.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @material do |f| %>

        <div class="field">
          <%= f.label :title, "素材名", class: "label" %>
          <%= f.text_field :title, class: "input" %>
        </div>

        <div class="field">
          <%= f.label :body, "概要欄", class: "label" %>
          <%= f.text_area :body, class: "textarea" %>
        </div>

        <div class="field">
          <%= f.label :video, "動画", class: "label" %>
          <%= f.file_field :video, class: "input" %>
        </div>

        <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/materials/index.html.erb
<section class="hero is-success">
  <div class="hero-body"> 
    <div　class="container">
      <h1 class="title">素材一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @materials.each do |material| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image ">
                <%= link_to material_path(material) do %>
                  <%= video_tag material.video, controls: true %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= link_to user_path(material.user.id) do %>
                      <%= attachment_image_tag material.user, :profile_image, fallback: "unknown-user.png" %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%= link_to material.user.username, user_path(material.user.id) %></div>
                </div>
                <div class="media-content">
                  <div class="content"><%= link_to material.title, material_path(material) %></div>
                </div>
                <div class="media-content">
                <% if current_user.already_liked?(material) %>
                  <%= link_to material_likes_path(material), method: :delete do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to material_likes_path(material), method: :post do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% end %>
                <%= material.likes.count %>
                </div>
              </div>
              
              <div class="content">
                <time><%= material.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/materials/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">新規投稿</h1>
    </div>
  </div>
</section>

<% if @material.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@material.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @material do |f| %>
          <div class="field">
            <%= f.label :title, "素材名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "概要欄", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
            <!--
            <%= f.label :image %>
            <%= f.attachment_field :image %>
            -->
          <div class="field">
            <%= f.label :video, "動画", class: "label" %>
            <%= f.file_field :video, class: "input", :accept => 'video/*' %>
          </div>
          <%= f.submit "投稿", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/materials/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        素材詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
            <div class="card-image">
              <figure class="image">
                  <%= video_tag @material.video, controls: true %>
              </figure>
            </div>
          <div class="card-content">
            <div class="madia">
              <div class="media-content">
                <p class="title is-4"><%= @material.title %></p>
              </div>
            </div>
            <div class="content">
              <div class="content">
                <% if current_user.already_liked?(@material) %>
                  <%= link_to material_likes_path(@material), method: :delete do %>
                  <i class="fas fa-heart"></i>
                  <% end %>
                <%= @material.likes.count %>
                <% else %>
                <%= link_to material_likes_path(@material), method: :post do %>
                <i class="far fa-heart"></i>
                <% end %>
                <%= @material.likes.count %>　
                <% end %>
              <div>
              <table class="table is-narrow">
                <tr>
                  <th>概要欄</th>
                </tr>
                <tr>
                  <td><%= simple_format @material.body %></td>
                </tr>
              </table>
              <% if @material.user.id == current_user.id %>
                <%= link_to "編集", edit_material_path(@material), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            <%= @material.user.username %>
          </p>
          <div class="panel-block">  
            <p class="control">
              <%= @material.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@material.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @material.user.username %>　さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">ユーザー編集画面</h1>
    </div>
  </div>  
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username ,class: "label"%>
            <%= f.text_field :username , class: "input"%>
          </div>

          <div class="field">
            <%= f.label :email , class: "label"%>
            <%= f.text_field :email , class: "input"%>
          </div>

          <div class="field">
            <%= f.label :profile , class: "label"%>
            <%= f.text_field :profile , class: "textarea"%>
          </div>

          <div class="field">
            <%= f.label :profile_image , class:"label"%>
            <%= f.attachment_field :profile_image , class: "input"%>
          </div>
          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-warning">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                投稿者一覧
            </h1>
        </div>
    </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do  %>
                    <%= attachment_image_tag user, :profile_image, :fill, 300, 300, fallback: "unknown-user.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%= link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                    投稿数：<%= user.materials.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <% if @user.id == current_user.id %>
        <h1 class="title">マイページ</h1>
      <% else %>
        <h1 class="title"><%= @user.username %>のプロフィール</h1>    
      <% end %>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, :fill, 300, 300, fallback: "unknown-user.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.materials.each do |material| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <%= link_to material_path(material) do %>
                  <%= video_tag material.video, controls: true %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="content">
                      素材名：<%= material.title %>
                  </div>
                  <%= link_to material_path(material), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-download" aria-hidden="true"></i>
                    </span>
                    この素材をダウンロード
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_material_path(material), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この素材を編集する
                    <% end %>
                    <%= link_to material_path(material), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この素材を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= material.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>